export const metadata = {
    title: "Project || Pucu - Nextjs Portfolio Template",
    description: "Generated by create next app",
  };

export default function ProjectLayout({ children }) {
    return <section>{children}</section>
  }