export const metadata = {
    title: "About || Pucu - Nextjs Portfolio Template",
    description: "Generated by create next app",
  };

export default function AboutLayout({ children }) {
    return <section>{children}</section>
  }